//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTest3.Client.CategoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseContract", Namespace="http://schemas.datacontract.org/2004/07/WcfTest3.Core.WcfContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfTest3.Client.CategoryService.PostContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfTest3.Client.CategoryService.CommentContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfTest3.Client.CategoryService.CategoryContract))]
    public partial class BaseContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostContract", Namespace="http://schemas.datacontract.org/2004/07/WcfTest3.Core.WcfContracts")]
    [System.SerializableAttribute()]
    public partial class PostContract : WcfTest3.Client.CategoryService.BaseContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTest3.Client.CategoryService.CategoryContract CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTest3.Client.CategoryService.CommentContract[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SentAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SentByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTest3.Client.CategoryService.CategoryContract Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTest3.Client.CategoryService.CommentContract[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentAt {
            get {
                return this.SentAtField;
            }
            set {
                if ((this.SentAtField.Equals(value) != true)) {
                    this.SentAtField = value;
                    this.RaisePropertyChanged("SentAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SentBy {
            get {
                return this.SentByField;
            }
            set {
                if ((object.ReferenceEquals(this.SentByField, value) != true)) {
                    this.SentByField = value;
                    this.RaisePropertyChanged("SentBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentContract", Namespace="http://schemas.datacontract.org/2004/07/WcfTest3.Core.WcfContracts")]
    [System.SerializableAttribute()]
    public partial class CommentContract : WcfTest3.Client.CategoryService.BaseContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTest3.Client.CategoryService.PostContract PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SentAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SentByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTest3.Client.CategoryService.PostContract Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentAt {
            get {
                return this.SentAtField;
            }
            set {
                if ((this.SentAtField.Equals(value) != true)) {
                    this.SentAtField = value;
                    this.RaisePropertyChanged("SentAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SentBy {
            get {
                return this.SentByField;
            }
            set {
                if ((object.ReferenceEquals(this.SentByField, value) != true)) {
                    this.SentByField = value;
                    this.RaisePropertyChanged("SentBy");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryContract", Namespace="http://schemas.datacontract.org/2004/07/WcfTest3.Core.WcfContracts")]
    [System.SerializableAttribute()]
    public partial class CategoryContract : WcfTest3.Client.CategoryService.BaseContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfTest3.Client.CategoryService.PostContract[] PostsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTest3.Client.CategoryService.PostContract[] Posts {
            get {
                return this.PostsField;
            }
            set {
                if ((object.ReferenceEquals(this.PostsField, value) != true)) {
                    this.PostsField = value;
                    this.RaisePropertyChanged("Posts");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoryService.ICategoryService")]
    public interface ICategoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/Get", ReplyAction="http://tempuri.org/ICategoryService/GetResponse")]
        WcfTest3.Client.CategoryService.CategoryContract Get(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/Get", ReplyAction="http://tempuri.org/ICategoryService/GetResponse")]
        System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.CategoryContract> GetAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/GetAll", ReplyAction="http://tempuri.org/ICategoryService/GetAllResponse")]
        WcfTest3.Client.CategoryService.CategoryContract[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/GetAll", ReplyAction="http://tempuri.org/ICategoryService/GetAllResponse")]
        System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.CategoryContract[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/GetCategoryPosts", ReplyAction="http://tempuri.org/ICategoryService/GetCategoryPostsResponse")]
        WcfTest3.Client.CategoryService.PostContract[] GetCategoryPosts(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/GetCategoryPosts", ReplyAction="http://tempuri.org/ICategoryService/GetCategoryPostsResponse")]
        System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.PostContract[]> GetCategoryPostsAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/Create", ReplyAction="http://tempuri.org/ICategoryService/CreateResponse")]
        WcfTest3.Client.CategoryService.CategoryContract Create(WcfTest3.Client.CategoryService.CategoryContract category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/Create", ReplyAction="http://tempuri.org/ICategoryService/CreateResponse")]
        System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.CategoryContract> CreateAsync(WcfTest3.Client.CategoryService.CategoryContract category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/Update", ReplyAction="http://tempuri.org/ICategoryService/UpdateResponse")]
        WcfTest3.Client.CategoryService.CategoryContract Update(WcfTest3.Client.CategoryService.CategoryContract category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/Update", ReplyAction="http://tempuri.org/ICategoryService/UpdateResponse")]
        System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.CategoryContract> UpdateAsync(WcfTest3.Client.CategoryService.CategoryContract category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/Delete", ReplyAction="http://tempuri.org/ICategoryService/DeleteResponse")]
        void Delete(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/Delete", ReplyAction="http://tempuri.org/ICategoryService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoryServiceChannel : WcfTest3.Client.CategoryService.ICategoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryServiceClient : System.ServiceModel.ClientBase<WcfTest3.Client.CategoryService.ICategoryService>, WcfTest3.Client.CategoryService.ICategoryService {
        
        public CategoryServiceClient() {
        }
        
        public CategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfTest3.Client.CategoryService.CategoryContract Get(int Id) {
            return base.Channel.Get(Id);
        }
        
        public System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.CategoryContract> GetAsync(int Id) {
            return base.Channel.GetAsync(Id);
        }
        
        public WcfTest3.Client.CategoryService.CategoryContract[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.CategoryContract[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public WcfTest3.Client.CategoryService.PostContract[] GetCategoryPosts(string Id) {
            return base.Channel.GetCategoryPosts(Id);
        }
        
        public System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.PostContract[]> GetCategoryPostsAsync(string Id) {
            return base.Channel.GetCategoryPostsAsync(Id);
        }
        
        public WcfTest3.Client.CategoryService.CategoryContract Create(WcfTest3.Client.CategoryService.CategoryContract category) {
            return base.Channel.Create(category);
        }
        
        public System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.CategoryContract> CreateAsync(WcfTest3.Client.CategoryService.CategoryContract category) {
            return base.Channel.CreateAsync(category);
        }
        
        public WcfTest3.Client.CategoryService.CategoryContract Update(WcfTest3.Client.CategoryService.CategoryContract category) {
            return base.Channel.Update(category);
        }
        
        public System.Threading.Tasks.Task<WcfTest3.Client.CategoryService.CategoryContract> UpdateAsync(WcfTest3.Client.CategoryService.CategoryContract category) {
            return base.Channel.UpdateAsync(category);
        }
        
        public void Delete(int Id) {
            base.Channel.Delete(Id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int Id) {
            return base.Channel.DeleteAsync(Id);
        }
    }
}
